### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [sahandnayebaziz/StateView#12]
`CocoaPods` is an awesome tool and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the _Manual installation_ guide in your `README.md`. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by sahandnayebaziz** [comment]
Thanks for the recommendation @lfarah. I plan to recommend CocoaPods as it is currently the easiest way to update external libraries as updates are made available. In the future, as the Swift Package Manager matures, I plan to support that as well.

**Comment by lfarah** [comment]
The problem on only having **CocoaPods** and **Swift Package Manager** is that some devs are still to new to programming and they don't know how to use it as the learning curve is kinda steep, so that's why I recommended adding a Manual option.
One other example is one of my clients who was trying to run my project and he asked me if there was an easier way for him to install the libraries instead of CocoaPods, since he doesn't use _Terminal_.
I understand your concerns regarding updating the library, but these users are not worried about updating. They just want it to make it work and build the project as fast as possible
