### ISSUE TITLE
Does StateView support Objective-C or OS X(NSView), too?

### ISSUE THREAD

**Issue by ryuheechul** [sahandnayebaziz/StateView#7]
It seems like a great idea that bringing react concept to native ios app.
So i would like to try StateView. Since I code mostly Objective-C for OS X, I am curious if StateView works with them.

**Comment by sahandnayebaziz** [comment]
@ryuheechul I would love for StateView to support Objective-C and NSViews, but it currently only supports Swift and UIViews. StateView is young. By the time it becomes a more mature library, it will have wide support for current and future Apple view programming libraries.

**Comment by ryuheechul** [comment]
@sahandnayebaziz sounds good :)
